resilience4j.retry:
  instances:
    failure-endpoint:
      maxAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - feign.FeignException$InternalServerError