management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  tomcat:
    threads:
      max: 15

resilience4j.retry:
  instances:
    failure-endpoint:
      maxAttempts: 3
      waitDuration: 2s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - feign.FeignException$InternalServerError

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
  instances:
    failure-endpoint:
      failureRateThreshold: 30
      registerHealthIndicator: true
      slidingWindowSize: 10
      waitDurationInOpenState: 60000
      permittedNumberOfCallsInHalfOpenState: 3
      recordExceptions:
        - feign.FeignException$InternalServerError

resilience4j.bulkhead:
  instances:
    response-time-endpoint:
      maxConcurrentCalls: 10
      maxWaitDuration: 10ms
